### ISSUE TITLE
previewAnyFile.previewBase64 error

### ISSUE THREAD

**Issue by lethieuluong** [mostafa-mansour1/previewAnyFile#32]
Hi,
I use previewAnyFile.previewBase64 in ionicvue to open base64 pdf like:

          previewAnyFile.previewBase64('data:application/pdf;base64,.......')
          .catch((error: any) => showError(error));

and got this error:
Error: the old format of this exec call has been removed (deprecated since 2.1). Change to: cordova.exec(null, null, 'Service', 'action', [arg1, arg2]);

I know you have a zip file provided for AngularJs as a fix, do you have a fix for Ionicvue, too ? e.g. correct the preview.js in 
\android\app\src\main\assets\public\plugins\cordova-plugin-preview-any-file\www

Thanks

**Comment by mostafa-mansour1** [comment]
I am not using ionic vue
Can you use direct cordova plugin?



window.PreviewAnyFile.previewBase64(
        win => console.log("open status",win),
        error => console.error("open failed", error),
        'JVBERi0xLjMKJcTl8uXr.....',{mimeType:'application/pdf'}
    );



Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 23 Jul 2021, at 7:46 PM, lethieuluong ***@***.***> wrote:

﻿

Hi,
I use previewAnyFile.previewBase64 in ionicvue to open base64 pdf like:

      previewAnyFile.previewBase64('data:application/pdf;base64,.......')
      .catch((error: any) => showError(error));


and got this error:
Error: the old format of this exec call has been removed (deprecated since 2.1). Change to: cordova.exec(null, null, 'Service', 'action', [arg1, arg2]);

I know you have a zip file provided for AngularJs as a fix, do you have a fix for Ionicvue, too ? e.g. correct the preview.js in
\android\app\src\main\assets\public\plugins\cordova-plugin-preview-any-file\www

Thanks

**Comment by lethieuluong** [comment]
if I use:

window.PreviewAnyFile.previewBase64

I got a compile error:

PreviewAnyFile does not exist on type windows

what I did is:

npm install cordova-plugin-preview-any-file
npm install @ionic-native/preview-any-file
ionic cap sync

what do it need else from code so that window.PreviewAnyFile is usable  ? sorry I'm pretty new with this topic. If you offer a support I will ask my company to purchase this. Thanks.

**Comment by mostafa-mansour1** [comment]
Use it like

(<any>window).PreviewAnyFile. previewBase64

Or

Let cloneWindow:any = window

cloneWindow.PreviewAnyFile. previewBase64



Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 24 Jul 2021, at 7:52 PM, lethieuluong ***@***.***> wrote:

﻿

if I use:

window.PreviewAnyFile.previewBase64

I got a compile error:

PreviewAnyFile does not exist on type windows

what I did is:

npm install cordova-plugin-preview-any-file
npm install @ionic-native/preview-any-file
ionic cap sync

what do it need else from code so that window.PreviewAnyFile is usable ? sorry I'm pretty new with this topic. If you offer a support I will ask my company to purchase this. Thanks.

**Comment by schnouz** [comment]
Hi, I Got the same error with previewBase64 even when calling from the window object.
